name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build easypost-cli
        run: ./utils/build.sh 1.0.0 bash
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run ShellCheck on /dist for bash
        uses: ludeeus/action-shellcheck@1.0.0
        with:
          scandir: "dist"
        env:
          SHELLCHECK_OPTS: -s bash
      - name: Run ShellCheck on /dist for sh
        uses: ludeeus/action-shellcheck@1.0.0
        with:
          scandir: "dist"
        env:
          SHELLCHECK_OPTS: -s sh
      - name: Run ShellCheck on /dist for dash
        uses: ludeeus/action-shellcheck@1.0.0
        with:
          scandir: "dist"
        env:
          SHELLCHECK_OPTS: -s dash
      - name: Run ShellCheck on /dist for ksh
        uses: ludeeus/action-shellcheck@1.0.0
        with:
          scandir: "dist"
        env:
          SHELLCHECK_OPTS: -s ksh
      - name: Run ShellCheck on /utils for bash
        uses: ludeeus/action-shellcheck@1.0.0
        with:
          scandir: "utils"
        env:
          SHELLCHECK_OPTS: -s bash
      - name: Run ShellCheck on /utils for sh
        uses: ludeeus/action-shellcheck@1.0.0
        with:
          scandir: "utils"
        env:
          SHELLCHECK_OPTS: -s sh
      - name: Run ShellCheck on /utils for dash
        uses: ludeeus/action-shellcheck@1.0.0
        with:
          scandir: "utils"
        env:
          SHELLCHECK_OPTS: -s dash
      - name: Run ShellCheck on /utils for ksh
        uses: ludeeus/action-shellcheck@1.0.0
        with:
          scandir: "utils"
        env:
          SHELLCHECK_OPTS: -s ksh
