on:
  push:
    tags:
      - "*"

jobs:
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - name: Release my project to my Homebrew tap
        uses: Justintime50/homebrew-releaser@v0.4.0
        with:
          commit_owner: Justintime50
          commit_email: justinpaulhammond@gmail.com
          homebrew_owner: Justintime50
          homebrew_tap: homebrew-formulas
          install: 'bin.install "dist/unix_ep.sh" => "ep"'
          github_token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
